name: Build Tracker Metadata

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  workflow_dispatch:
      
permissions:
  contents: read
  pages: write
  id-token: write
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup node environment
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Build apps with Parcel
        run: npm run build:parcel || true

      - name: Build apps with Rollup
        run: npm run build:rollup || true

      - name: Build metadata.json
        run: npm run build:metadata

      - name: Build README.md
        run: npm run build:readme
